// Generated by CoffeeScript 2.6.1
(function() {
  var fs, main, readline;

  fs = require("fs");

  readline = require('readline-sync');

  main = function() {
    var counter, i, inputFileName, inputText, j, ref;
    inputFileName = readline.question("Enter input filename: ");
    inputText = fs.readFileSync(inputFileName).toString().split(/\n/).map(parseInt);
    counter = 0;
    for (i = j = 0, ref = inputText.length - 1; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
      counter += inputText[i] > inputText[i - 1] ? 1 : 0;
    }
    return console.log(`Counter: ${counter}`);
  };

  main();

}).call(this);
